// Code generated by MockGen. DO NOT EDIT.
// Source: dash0.com/otlp-log-processor-backend/internal/sink (interfaces: Sink)
//
// Generated by this command:
//
//	mockgen -destination internal/mocks/mock_sink.go -package mocks dash0.com/otlp-log-processor-backend/internal/sink Sink
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sink "dash0.com/otlp-log-processor-backend/internal/sink"
	gomock "go.uber.org/mock/gomock"
)

// MockSink is a mock of Sink interface.
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
	isgomock struct{}
}

// MockSinkMockRecorder is the mock recorder for MockSink.
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance.
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockSink) Publish(ctx context.Context, s sink.Snapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockSinkMockRecorder) Publish(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSink)(nil).Publish), ctx, s)
}
